COMP: missing include
"
/home/nr52/gitroot/gofigure/Main/QGoMainWindow.cxx:952: error: variable ‘QTextStream textStream’ has initializer but incomplete type
"